open_system('gm_stream_adaptation_model');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_stream_adaptation_model/stream_adapt/frame_counter', 'user1');
annotate_port('gm_stream_adaptation_model/stream_adapt/frame_counter', 0, 1, 'cp : 0.474 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_stream_adaptation_model/stream_adapt/reset_out15', 'user2');
annotate_port('gm_stream_adaptation_model/stream_adapt/reset_out15', 0, 1, 'cp : 1.762 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_stream_adaptation_model/stream_adapt/Compare To Constant', 'user2');
annotate_port('gm_stream_adaptation_model/stream_adapt/Compare To Constant', 0, 1, 'cp : 1.345 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_stream_adaptation_model/stream_adapt/Compare To Constant1', 'user2');
annotate_port('gm_stream_adaptation_model/stream_adapt/Compare To Constant1', 0, 1, 'cp : 2.508 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_stream_adaptation_model/stream_adapt/Logical Operator1', 'user1');
annotate_port('gm_stream_adaptation_model/stream_adapt/Logical Operator1', 0, 1, 'cp : 4.5235 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_stream_adaptation_model/stream_adapt/Logical Operator3', 'user2');
annotate_port('gm_stream_adaptation_model/stream_adapt/Logical Operator3', 0, 1, 'cp : 3.1235 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_stream_adaptation_model/stream_adapt/Switch1', 'user2');
annotate_port('gm_stream_adaptation_model/stream_adapt/Switch1', 0, 1, 'cp : 3.5405 ns');
