set_property SRC_FILE_INFO {cfile:d:/Documents/DVBS2/DVBS2/src/transmitter/3-FEC/hdl_prj/fil_prj/fpgaproj/ldpc_encoder_fil.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../ldpc_encoder_fil.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:u_clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Documents/DVBS2/DVBS2/src/transmitter/3-FEC/hdl_prj/fil_prj/fpgaproj/ldpc_encoder_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo_in_context.xdc rfile:../../../../../ldpc_encoder_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo_in_context.xdc id:2 order:EARLY scoped_inst:u_jtag_mac/u_pre_chif_fifo/u_jtag_mac_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Documents/DVBS2/DVBS2/src/transmitter/3-FEC/hdl_prj/fil_prj/fpgaproj/ldpc_encoder_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo_in_context.xdc rfile:../../../../../ldpc_encoder_fil.gen/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo/jtag_mac_fifo_in_context.xdc id:3 order:EARLY scoped_inst:u_jtag_mac/u_post_chif_fifo/u_jtag_mac_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Documents/DVBS2/DVBS2/src/transmitter/3-FEC/hdl_prj/fil_prj/fpgaproj/ldpc_encoder_fil.gen/sources_1/ip/simcycle_fifo/simcycle_fifo/simcycle_fifo_in_context.xdc rfile:../../../../../ldpc_encoder_fil.gen/sources_1/ip/simcycle_fifo/simcycle_fifo/simcycle_fifo_in_context.xdc id:4 order:EARLY scoped_inst:u_jtag_mac/u_simcycle_fifo/u_simcycle_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Documents/DVBS2/DVBS2/src/transmitter/3-FEC/hdl_prj/fil_prj/filsrc/ldpc_encoder_fil.xdc rfile:../../../../../../filsrc/ldpc_encoder_fil.xdc id:5} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sysclk [get_ports sysclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name u_clk_wiz_0/clk_out1 -source [get_pins u_clk_wiz_0/clk_in1] -edges {1 2 3} -edge_shift {0.000 15.000 30.000} [get_pins u_clk_wiz_0/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sysclk]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sysclk]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_clk_wiz_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_jtag_mac/u_pre_chif_fifo/u_jtag_mac_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_jtag_mac/u_pre_chif_fifo/u_jtag_mac_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_jtag_mac/u_pre_chif_fifo/u_jtag_mac_fifo]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_jtag_mac/u_post_chif_fifo/u_jtag_mac_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_jtag_mac/u_post_chif_fifo/u_jtag_mac_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_jtag_mac/u_post_chif_fifo/u_jtag_mac_fifo]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_jtag_mac/u_simcycle_fifo/u_simcycle_fifo/rd_clk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_jtag_mac/u_simcycle_fifo/u_simcycle_fifo/wr_clk]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_jtag_mac/u_simcycle_fifo/u_simcycle_fifo]
set_property src_info {type:XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sysclk -waveform {0.000 5.000} [get_ports sysclk]
set_property src_info {type:XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
set_property src_info {type:XDC file:5 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports sysrst]
set_property src_info {type:XDC file:5 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 15.152 -name TCK -waveform {0.000 7.576} [get_pins u_BSCANE2/TCK]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_clk_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_jtag_mac/u_pre_chif_fifo/u_jtag_mac_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_jtag_mac/u_post_chif_fifo/u_jtag_mac_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_jtag_mac/u_simcycle_fifo/u_simcycle_fifo]
