classdef (StrictDefaults)class_mlhdlc_sysobj_ex_fixpt_sysobj <  hdlverifier.FILSimulation
%class_mlhdlc_sysobj_ex_fixpt_sysobj is a filWizard generated class used for FPGA-In-the-Loop
%   simulation with the 'mlhdlc_sysobj_ex_fixpt' DUT.
%   class_mlhdlc_sysobj_ex_fixpt_sysobj connects MATLAB with a FPGA and cosimulate with it by 
%   writing inputs in the FPGA and reading outputs from the FPGA.
%
%   MYFIL = class_mlhdlc_sysobj_ex_fixpt_sysobj
%
%   Step method syntax:
%
%   [out1, out2, ...] = step(MYFIL, in1, in2, ...) connect to the FPGA,
%   write in1, in2, ... to the FPGA and read out1, out2, ... from 
%   the FPGA
%
%   class_mlhdlc_sysobj_ex_fixpt_sysobj methods:
%
%   step        - See above description for use of this method
%   release     - Allow property value and input characteristics changes, and
%                 release connection to FPGA board
%   clone       - Create class_mlhdlc_sysobj_ex_fixpt_sysobj object with same property values
%   isLocked    - Locked status (logical)
%   programFPGA - Load the programming file in the FPGA
%
%   class_mlhdlc_sysobj_ex_fixpt_sysobj properties:
%
%   DUTName                  - DUT top level name
%   InputSignals             - Input paths in the HDL code
%   InputBitWidths           - Width in bit of the inputs
%   OutputSignals            - Output paths in the HDL code
%   OutputBitWidths          - Width in bit of the outputs
%   OutputDataTypes          - Data type of the outputs
%   OutputSigned             - Sign of the outputs
%   OutputFractionLengths    - Fraction lengths of the outputs
%   OutputDownsampling       - Downsampling factor and phase of the outputs
%   OverclockingFactor       - Overclocking factor of the hardware
%   Connection               - Parameters for the connection with the board
%   FPGAVendor               - Name of the FPGA chip vendor
%   FPGABoard                - Name of the FPGA board
%   FPGAProgrammingFile      - Path of the Programming file for the FPGA
%   ScanChainPosition        - Position of the FPGA in the JTAG scan chain
%
%   File Name: class_mlhdlc_sysobj_ex_fixpt_sysobj.m
%   Created: 29-Nov-2020 19:48:19
% 
%   Generated by FIL Wizard

%#codegen

    properties (Nontunable)
        DUTName = 'mlhdlc_sysobj_ex_fixpt';
    end
    
    methods
        function obj = class_mlhdlc_sysobj_ex_fixpt_sysobj
            
            %THE FOLLOWING PROTECTED PROPERTIES ARE SPECIFIC TO THE HW DUT
            %AND MUST NOT BE EDITED (RERUN THE FIL WIZARD TO CHANGE THEM)
            obj.InputSignals = char('x_in','h_in1','h_in2','h_in3','h_in4');
            obj.InputBitWidths = [14,14,14,14,14];
            obj.OutputSignals = char('y_out','delayed_xout');
            obj.OutputBitWidths = [14,14];
            obj.Connection = char('JTAG','libmwrtiostream_xjtag','FPGAInstr=000010;FPGAInstr2=000011;FPGAInstr3=100010;FPGAInstr4=100011;InstrLenBefore=0;InstrLenAfter=0;TckFrequency=66.000000',''); 
            obj.FPGAVendor = 'Xilinx';
            obj.FPGATool   = 'Xilinx Vivado';
            obj.FPGABoard = 'My Arty Z7';
            obj.ScanChainPosition = 1 ;
            
            %THE FOLLOWING PUBLIC PROPERTIES ARE RELATED TO THE SIMULATION
            %AND CAN BE EDITED WITHOUT RERUNING THE FIL WIZARD
            obj.OutputSigned = [true,true];
            obj.OutputDataTypes = char('fixedpoint','fixedpoint');
            obj.OutputFractionLengths = [12,12];
            obj.OutputDownsampling = [1,0];
            obj.OverclockingFactor = 1;
            obj.FPGAProgrammingFile = '/home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/mlhdlc_sysobj_ex_fixpt_fil.bit';                       
        end
    end
end




