%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.9 and Fixed-Point Designer 7.1           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MATLAB design: Symmetric FIR Filter
% 
% Design pattern covered in this example: 
%  Filter states modeled using DSP System object (dsp.Delay)
%  Filter coefficients passed in as parameters to the design
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Copyright 2011-2015 The MathWorks, Inc.
%#codegen
function [y_out, delayed_xout] = mlhdlc_sysobj_ex_fixpt(x_in, h_in1, h_in2, h_in3, h_in4)
% Symmetric FIR Filter

fm = get_fimath();

persistent h1 h2 h3 h4 h5 h6 h7 h8;
if isempty(h1)
    h1 = dsp.Delay;
    h2 = dsp.Delay;
    h3 = dsp.Delay;
    h4 = dsp.Delay;
    h5 = dsp.Delay;
    h6 = dsp.Delay;
    h7 = dsp.Delay;
    h8 = dsp.Delay;
end

h1p = fi(step(h1, x_in), 1, 14, 12, fm);
h2p = fi(step(h2, h1p), 1, 14, 12, fm);
h3p = fi(step(h3, h2p), 1, 14, 12, fm);
h4p = fi(step(h4, h3p), 1, 14, 12, fm);
h5p = fi(step(h5, h4p), 1, 14, 12, fm);
h6p = fi(step(h6, h5p), 1, 14, 12, fm);
h7p = fi(step(h7, h6p), 1, 14, 12, fm);
h8p = fi(step(h8, h7p), 1, 14, 12, fm);

a1 = fi(h1p + h8p, 1, 14, 12, fm);
a2 = fi(h2p + h7p, 1, 14, 12, fm);
a3 = fi(h3p + h6p, 1, 14, 12, fm);
a4 = fi(h4p + h5p, 1, 14, 11, fm);

m1 = fi(h_in1 * a1, 1, 14, 14, fm);
m2 = fi(h_in2 * a2, 1, 14, 15, fm);
m3 = fi(h_in3 * a3, 1, 14, 14, fm);
m4 = fi(h_in4 * a4, 1, 14, 13, fm);

a5 = fi(m1 + m2, 1, 14, 14, fm);
a6 = fi(m3 + m4, 1, 14, 12, fm);

% filtered output
y_out = fi(a5 + a6, 1, 14, 12, fm);
% delayout input signal
delayed_xout = fi(h8p, 1, 14, 12, fm);

end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
