-- -------------------------------------------------------------
-- 
-- File Name: D:\Documents\DVBS2\DVBS2\src\transmitter\3-FEC\ldpc\altera_files\hdlsrc\ldpc_dvbs2_model_v2\MATLAB_Function.vhd
-- Created: 2021-01-31 19:23:01
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: ldpc_dvbs2_model_v2/ldpc_encoder/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ldpc_encoder_pac.ALL;

ENTITY MATLAB_Function IS
  PORT( parity_in                         :   IN    std_logic_vector(0 TO 16200);  -- ufix1 [16201]
        addresses                         :   IN    vector_of_std_logic_vector16(0 TO 11);  -- uint16 [12]
        input_bit                         :   IN    std_logic;
        parity_out                        :   OUT   std_logic_vector(0 TO 16200)  -- ufix1 [16201]
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  ATTRIBUTE multstyle : string;

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;

  -- HDLCODER_TO_SIGNED
  FUNCTION hdlcoder_to_signed(arg: boolean; width: integer) RETURN signed IS
  BEGIN
    IF arg THEN
      RETURN to_signed(1, width);
    ELSE
      RETURN to_signed(0, width);
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL addresses_unsigned               : vector_of_unsigned16(0 TO 11);  -- uint16 [12]

BEGIN
  outputgen: FOR k IN 0 TO 11 GENERATE
    addresses_unsigned(k) <= unsigned(addresses(k));
  END GENERATE;

  MATLAB_Function_1_output : PROCESS (addresses_unsigned, input_bit, parity_in)
    VARIABLE add_temp : vector_of_unsigned16(0 TO 11);
    VARIABLE sub_cast : vector_of_signed32(0 TO 11);
    VARIABLE add_temp_0 : vector_of_unsigned16(0 TO 11);
    VARIABLE sub_cast_0 : vector_of_signed32(0 TO 11);
    VARIABLE cast : vector_of_signed32(0 TO 11);
  BEGIN
    --MATLAB Function 'ldpc_encoder/MATLAB Function'

    FOR t_0 IN 0 TO 16200 LOOP
      parity_out(t_0) <= parity_in(t_0);
    END LOOP;


    FOR t_1 IN 0 TO 11 LOOP
      add_temp(t_1) := addresses_unsigned(t_1) + 1;
      sub_cast(t_1) := signed(resize(add_temp(t_1), 32));
      add_temp_0(t_1) := addresses_unsigned(t_1) + 1;
      sub_cast_0(t_1) := signed(resize(add_temp_0(t_1), 32));
      cast(t_1) := '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & input_bit;
      parity_out(to_integer(sub_cast(t_1) - 1)) <= hdlcoder_to_stdlogic(hdlcoder_to_signed(parity_in(to_integer(sub_cast_0(t_1) - 1)) /= '0', 32) /= cast(t_1));
    END LOOP;

  END PROCESS MATLAB_Function_1_output;


END rtl;

