-- -------------------------------------------------------------
-- 
-- File Name: D:\Documents\DVBS2\DVBS2\src\transmitter\3-FEC\interleaver\xilinx_files\hdlsrc\interleaver_model\interleaver_dut_pac.vhd
-- Created: 2021-02-01 12:53:54
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE interleaver_dut_pac IS
  TYPE matrix_of_std_logic IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF std_logic;
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
END interleaver_dut_pac;

