SLStudio.Utils.RemoveHighlighting(get_param('ldpc_dvbs2_model_v2', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ldpc_dvbs2_model_v2', 'handle'));
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank', 0, 12, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay_Switch', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay1_lowered', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Logical Operator', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor10', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor11', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor5', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor8', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 0, 2, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/select_address/select_address', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/select_address/select_address', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/select_address', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses1', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 0, 2, '');
