open_system('gm_ldpc_dvbs2_model_v2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank', 0, 12, 'cp : 3.1425 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay_Switch', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay_Switch', 0, 1, 'cp : 8.453 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay1_lowered', 'user1');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay1_lowered', 1, 1, 'cp : 8.617 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Logical Operator', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Logical Operator', 0, 1, 'cp : 7.98 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor10', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor10', 0, 1, 'cp : 6.0915 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor11', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor11', 0, 1, 'cp : 7.0745 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor5', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor5', 0, 1, 'cp : 4.1255 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor8', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/global_xor8', 0, 1, 'cp : 5.1085 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11', 0, 1, 'cp : 3.1425 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 0, 2, 'cp : 3.1425 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user1');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 0, 2, 'cp : 3.1425 ns');
