open_system('ldpc_dvbs2_model_v2');
open_system('gm_ldpc_dvbs2_model_v2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/select_address/select_address', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/select_address/select_address', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/select_address/select_address', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/select_address/select_address', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/select_address', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/select_address', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses1', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses1', 1, 1, 'Block not characterized');
hilite_system('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses', 'user2');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
