vlib work
vcom  ldpc_encoder_pac.vhd
vcom  addresses.vhd
vcom  address_calculator.vhd
vcom  DualPortRAM_singlebit.vhd
vcom  ram_repeat.vhd
vcom  ram_repeat1.vhd
vcom  ram_repeat10.vhd
vcom  ram_repeat11.vhd
vcom  ram_repeat2.vhd
vcom  ram_repeat3.vhd
vcom  ram_repeat4.vhd
vcom  ram_repeat5.vhd
vcom  ram_repeat6.vhd
vcom  ram_repeat7.vhd
vcom  ram_repeat8.vhd
vcom  ram_repeat9.vhd
vcom  ram_bank.vhd
vcom  select_address.vhd
vcom  ldpc_encoder.vhd
