# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/vivado_prj/tran_dut_vivado.runs/synth_1/tran_dut.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/vivado_prj/tran_dut_vivado.cache/wt [current_project]
set_property parent.project_path /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/vivado_prj/tran_dut_vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/tran_dut_pac.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/Cosine_HDL_Optimized.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/DualPortRAM_singlebit.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/FIR_Interpolation.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/FIR_Interpolation1.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/SinglePortRAM_singlebit.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/addresses.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/address_calculator.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/angle_selector.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/bb_shaping1.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/output_mask.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/registers.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/shift_and_xor.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/p2s.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/bch_encoder.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/bit_mapping.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/interleaver_dut.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/select_address.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat1.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat2.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat3.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat4.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat5.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat6.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat7.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat8.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat9.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat10.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_repeat11.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ram_bank.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/ldpc_encoder.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/stream_adapt.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/tran_dut_tc.vhd
  /home/wardo/Documents/DVBS2/DVBS2/src/hdl_prj/hdlsrc/transmitter/tran_dut.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top tran_dut -part xc7z020clg400-1 -mode out_of_context
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tran_dut.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tran_dut_utilization_synth.rpt -pb tran_dut_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
