-- -------------------------------------------------------------
-- 
-- File Name: /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/angle_selector.vhd
-- Created: 2021-02-07 15:24:31
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: angle_selector
-- Source Path: transmitter/tran_dut/bit_mapping/angle_selector
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY angle_selector IS
  PORT( input                             :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        phase                             :   OUT   std_logic_vector(22 DOWNTO 0)  -- ufix23_En14
        );
END angle_selector;


ARCHITECTURE rtl OF angle_selector IS

  ATTRIBUTE multstyle : string;

  -- Signals
  SIGNAL input_unsigned                   : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL phase_tmp                        : unsigned(22 DOWNTO 0);  -- ufix23_En14

BEGIN
  input_unsigned <= unsigned(input);

  angle_selector_1_output : PROCESS (input_unsigned)
    VARIABLE tmp : signed(31 DOWNTO 0);
  BEGIN
    -- Receives a bit sequence and returns the angle in radians of the
    -- corresponding 8-psk constellation symbol. Gray encoding is used as stated
    -- in the DVB-S2 standard.
    tmp := to_signed(16#00000000#, 32);
    -- Start at phase 0
    IF input_unsigned = to_unsigned(16#1#, 3) THEN 
      NULL;
    ELSIF input_unsigned = to_unsigned(16#0#, 3) THEN 
      tmp := to_signed(16#0000002D#, 32);
    ELSIF input_unsigned = to_unsigned(16#4#, 3) THEN 
      tmp := to_signed(16#0000005A#, 32);
    ELSIF input_unsigned = to_unsigned(16#6#, 3) THEN 
      tmp := to_signed(16#00000087#, 32);
    ELSIF input_unsigned = to_unsigned(16#2#, 3) THEN 
      tmp := to_signed(16#000000B4#, 32);
    ELSIF input_unsigned = to_unsigned(16#3#, 3) THEN 
      tmp := to_signed(16#000000E1#, 32);
    ELSIF input_unsigned = to_unsigned(16#7#, 3) THEN 
      tmp := to_signed(16#0000010E#, 32);
    ELSIF input_unsigned = to_unsigned(16#5#, 3) THEN 
      tmp := to_signed(16#0000013B#, 32);
    END IF;
    -- 9 bits necessary to represent 360 degrees.
    phase_tmp <= unsigned(tmp(8 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0');
  END PROCESS angle_selector_1_output;


  phase <= std_logic_vector(phase_tmp);

END rtl;

