SLStudio.Utils.RemoveHighlighting(get_param('transmitter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_transmitter', 'handle'));
annotate_port('gm_transmitter/tran_dut/bb_shaping1', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/stream_adapt', 1, 1, '');
annotate_port('transmitter/tran_dut/stream_adapt', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/registers', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Divide', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Divide', 1, 1, '');
annotate_port('transmitter/tran_dut/bit_mapping/Divide', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Amp50', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En21', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En31', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En4', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/QuadHandle1', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/QuadHandle21', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Saturation1', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Switch1', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/insig1', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/p50mA', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/PipelineRegister1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut1/interleaver', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut1/interleaver', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/slot_counter', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/slot_counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/bit_counter1', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/bit_counter1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/stream_adapt/frame_counter', 1, 1, '');
annotate_port('transmitter/tran_dut/stream_adapt/frame_counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/output_mask/output_mask', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/output_mask/output_mask', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/output_mask', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/registers', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/registers', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/shift_and_xor/shift_and_xor', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/shift_and_xor/shift_and_xor', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/shift_and_xor', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 0, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 1, 1, '');
annotate_port('transmitter/tran_dut/bit_mapping/angle_selector', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut1/interleaver', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut1/interleaver', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/MATLAB Function/MATLAB Function', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/MATLAB Function/MATLAB Function', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/MATLAB Function', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses1', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/addresses', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, '');
