open_system('gm_transmitter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping', 0, 1, 'cp : 26.73 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized', 1, 1, 'cp : 26.73 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/angle_selector', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Divide', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Divide', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Amp50', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Amp50', 0, 1, 'cp : 3.793 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En21', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En21', 0, 1, 'cp : 9.881 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En31', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En31', 0, 1, 'cp : 11.922 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En4', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/CastU16En4', 0, 1, 'cp : 9.881 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Look-Up Table1', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Look-Up Table1', 0, 1, 'cp : 26.373 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/QuadHandle1', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/QuadHandle1', 0, 1, 'cp : 4.481 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/QuadHandle21', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/QuadHandle21', 0, 1, 'cp : 9.881 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Saturation1', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Saturation1', 0, 1, 'cp : 13.238 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Switch1', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/Switch1', 0, 1, 'cp : 13.403 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/insig1', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/insig1', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/p50mA', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/p50mA', 0, 1, 'cp : 9.193 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/PipelineRegister1', 'user1');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Cosine HDL Optimized/PipelineRegister1', 1, 1, 'cp : 26.73 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 0, 1, 'cp : 0 ns');
