open_system('transmitter');
open_system('gm_transmitter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation', 'user2');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 'user2');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation', 'user2');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 'user2');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 'user2');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 'user2');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 'user2');
annotate_port('gm_transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 'user2');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/Divide', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/Divide', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bit_mapping/Divide', 'user2');
annotate_port('transmitter/tran_dut/bit_mapping/Divide', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/output_mask/output_mask', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/output_mask/output_mask', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/output_mask/output_mask', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/output_mask/output_mask', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bch_encoder/output_mask', 'user2');
annotate_port('transmitter/tran_dut/bch_encoder/output_mask', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bch_encoder/p2s', 'user2');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/registers/registers', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/registers/registers', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bch_encoder/registers', 'user2');
annotate_port('transmitter/tran_dut/bch_encoder/registers', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/shift_and_xor/shift_and_xor', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/shift_and_xor/shift_and_xor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/shift_and_xor/shift_and_xor', 'user2');
annotate_port('gm_transmitter/tran_dut/bch_encoder/shift_and_xor/shift_and_xor', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bch_encoder/shift_and_xor', 'user2');
annotate_port('transmitter/tran_dut/bch_encoder/shift_and_xor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 'user2');
annotate_port('gm_transmitter/tran_dut/bit_mapping/angle_selector/angle_selector', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/bit_mapping/angle_selector', 'user2');
annotate_port('transmitter/tran_dut/bit_mapping/angle_selector', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 'user2');
annotate_port('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 'user2');
annotate_port('gm_transmitter/tran_dut/interleaver_dut1/interleaver/interleaver', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/interleaver_dut1/interleaver', 'user2');
annotate_port('transmitter/tran_dut/interleaver_dut1/interleaver', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/MATLAB Function/MATLAB Function', 'user2');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/MATLAB Function/MATLAB Function', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/ldpc_encoder/MATLAB Function', 'user2');
annotate_port('transmitter/tran_dut/ldpc_encoder/MATLAB Function', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 'user2');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 'user2');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/ldpc_encoder/p2s', 'user2');
annotate_port('transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses', 'user2');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses', 'user2');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses1', 'user2');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/addresses/addresses1', 1, 1, 'Block not characterized');
hilite_system('transmitter/tran_dut/ldpc_encoder/address_calculator/addresses', 'user2');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/addresses', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 'user2');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 'user2');
annotate_port('transmitter/tran_dut/bb_shaping1/FIR Interpolation1', 1, 1, 'Block not characterized');
