-- -------------------------------------------------------------
-- 
-- File Name: /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/tran_dut.vhd
-- Created: 2021-02-07 15:24:31
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.258222
-- Target subsystem base rate: 0.258222
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.258222
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- inphase                       ce_out        0.258222
-- quadrature                    ce_out        0.258222
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: tran_dut
-- Source Path: transmitter/tran_dut
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.tran_dut_pac.ALL;

ENTITY tran_dut IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        input_bit                         :   IN    std_logic;  -- ufix1
        amplitude                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        start                             :   IN    std_logic;
        end_rsvd                          :   IN    std_logic;
        valid                             :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        inphase                           :   OUT   std_logic_vector(44 DOWNTO 0);  -- sfix45_En31
        quadrature                        :   OUT   std_logic_vector(44 DOWNTO 0)  -- sfix45_En31
        );
END tran_dut;


ARCHITECTURE rtl OF tran_dut IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT tran_dut_tc
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb                             :   OUT   std_logic;
          enb_1_1_1                       :   OUT   std_logic;
          enb_1_8_0                       :   OUT   std_logic;
          enb_1_8_1                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT stream_adapt
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_8_1                       :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          input_bit                       :   IN    std_logic;  -- ufix1
          start                           :   IN    std_logic;
          valid                           :   IN    std_logic;
          end_rsvd                        :   IN    std_logic;
          out_rsvd                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT bch_encoder
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_8_1                       :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          in_rsvd                         :   IN    std_logic;
          end_of_frame                    :   IN    std_logic;
          out_rsvd                        :   OUT   std_logic;  -- ufix1
          valid                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT ldpc_encoder
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_8_1                       :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          input_bit                       :   IN    std_logic;
          start                           :   IN    std_logic;
          end_of_frame                    :   IN    std_logic;
          out_rsvd                        :   OUT   std_logic;  -- ufix1
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT interleaver_dut
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_8_1                       :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          input_bit                       :   IN    std_logic;
          valid                           :   IN    std_logic;
          end_rsvd                        :   IN    std_logic;
          data_out                        :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
          valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT bit_mapping
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb                             :   IN    std_logic;
          input_sequence                  :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          amplitude                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          inphase                         :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En15
          quadrature                      :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En15
          );
  END COMPONENT;

  COMPONENT bb_shaping1
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_1_1                       :   IN    std_logic;
          inphase                         :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En15
          quadrature                      :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En15
          i_filtered                      :   OUT   std_logic_vector(44 DOWNTO 0);  -- sfix45_En31
          q_filtered                      :   OUT   std_logic_vector(44 DOWNTO 0)  -- sfix45_En31
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : tran_dut_tc
    USE ENTITY work.tran_dut_tc(rtl);

  FOR ALL : stream_adapt
    USE ENTITY work.stream_adapt(rtl);

  FOR ALL : bch_encoder
    USE ENTITY work.bch_encoder(rtl);

  FOR ALL : ldpc_encoder
    USE ENTITY work.ldpc_encoder(rtl);

  FOR ALL : interleaver_dut
    USE ENTITY work.interleaver_dut(rtl);

  FOR ALL : bit_mapping
    USE ENTITY work.bit_mapping(rtl);

  FOR ALL : bb_shaping1
    USE ENTITY work.bb_shaping1(rtl);

  -- Signals
  SIGNAL enb_1_1_1                        : std_logic;
  SIGNAL enb_1_8_1                        : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL enb_1_8_0                        : std_logic;
  SIGNAL start_1                          : std_logic;
  SIGNAL stream_adapt_out1                : std_logic;
  SIGNAL HDL_Counter_out1                 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL Compare_To_Constant2_out1_1      : std_logic;
  SIGNAL serial_out                       : std_logic;  -- ufix1
  SIGNAL valid_1                          : std_logic;  -- ufix1
  SIGNAL valid_2                          : std_logic;  -- ufix1
  SIGNAL valid_3                          : std_logic;  -- ufix1
  SIGNAL delayMatch8_reg                  : std_logic_vector(0 TO 7);  -- ufix1 [8]
  SIGNAL delayMatch8_reg_next             : std_logic_vector(0 TO 7);  -- ufix1 [8]
  SIGNAL stream_adapt_out1_1              : std_logic;
  SIGNAL serial_out_1                     : std_logic;  -- ufix1
  SIGNAL serial_out_2                     : std_logic;  -- ufix1
  SIGNAL Switch2_out1                     : std_logic;
  SIGNAL delayMatch9_reg                  : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL delayMatch9_reg_next             : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL From1_out1                       : std_logic;
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL delayMatch10_reg                 : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL delayMatch10_reg_next            : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Compare_To_Constant_out1_1       : std_logic;
  SIGNAL ldpc_encoder_out1                : std_logic;  -- ufix1
  SIGNAL ldpc_encoder_out2                : std_logic;
  SIGNAL ldpc_encoder_out2_1              : std_logic;
  SIGNAL ldpc_encoder_out2_2              : std_logic;
  SIGNAL Switch3_out1                     : std_logic;
  SIGNAL delayMatch11_reg                 : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL delayMatch11_reg_next            : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Compare_To_Constant1_out1_1      : std_logic;
  SIGNAL delayMatch12_reg                 : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL delayMatch12_reg_next            : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Logical_Operator_out1_1          : std_logic;
  SIGNAL y                                : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL interleaver_dut_out2             : std_logic;
  SIGNAL delayMatch14_reg                 : std_logic_vector(0 TO 7);  -- ufix1 [8]
  SIGNAL delayMatch14_reg_next            : std_logic_vector(0 TO 7);  -- ufix1 [8]
  SIGNAL interleaver_dut_out2_1           : std_logic;
  SIGNAL interleaver_dut_out2_2           : std_logic;
  SIGNAL interleaver_dut_out2_dtc         : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL amplitude_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL delayMatch13_reg                 : vector_of_unsigned8(0 TO 2);  -- ufix8 [3]
  SIGNAL delayMatch13_reg_next            : vector_of_unsigned8(0 TO 2);  -- ufix8 [3]
  SIGNAL amplitude_1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL From_out1                        : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL bit_mapping_out1                 : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL bit_mapping_out2                 : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL bit_mapping_out1_signed          : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL Switch_out1                      : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL interleaver_dut_out2_dtc_1       : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL bit_mapping_out2_signed          : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL Switch1_out1                     : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL FIR_Interpolation_bypass_reg     : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL Switch_out1_1                    : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL FIR_Interpolation1_bypass_reg    : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL Switch1_out1_1                   : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL bb_shaping1_out1                 : std_logic_vector(44 DOWNTO 0);  -- ufix45
  SIGNAL bb_shaping1_out2                 : std_logic_vector(44 DOWNTO 0);  -- ufix45

BEGIN
  -- Pulse Shaping
  -- 
  -- Constellation Mapping
  -- 
  -- Forward Error Correction
  -- 
  -- Stream Adaptation

  u_tran_dut_tc : tran_dut_tc
    PORT MAP( clk => clk,
              reset_x => reset_x,
              clk_enable => clk_enable,
              enb => enb,
              enb_1_1_1 => enb_1_1_1,
              enb_1_8_0 => enb_1_8_0,
              enb_1_8_1 => enb_1_8_1
              );

  u_stream_adapt : stream_adapt
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_8_1 => enb_1_8_1,
              enb => enb,
              enb_1_8_0 => enb_1_8_0,
              input_bit => input_bit,  -- ufix1
              start => start_1,
              valid => valid,
              end_rsvd => end_rsvd,
              out_rsvd => stream_adapt_out1
              );

  u_bch_encoder : bch_encoder
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_8_1 => enb_1_8_1,
              enb => enb,
              enb_1_8_0 => enb_1_8_0,
              in_rsvd => stream_adapt_out1,
              end_of_frame => Compare_To_Constant2_out1_1,
              out_rsvd => serial_out,  -- ufix1
              valid => valid_1  -- ufix1
              );

  u_ldpc_encoder : ldpc_encoder
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_8_1 => enb_1_8_1,
              enb => enb,
              enb_1_8_0 => enb_1_8_0,
              input_bit => Switch2_out1,
              start => From1_out1,
              end_of_frame => Compare_To_Constant_out1_1,
              out_rsvd => ldpc_encoder_out1,  -- ufix1
              valid_out => ldpc_encoder_out2
              );

  u_interleaver_dut : interleaver_dut
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_8_1 => enb_1_8_1,
              enb => enb,
              enb_1_8_0 => enb_1_8_0,
              input_bit => Switch3_out1,
              valid => Compare_To_Constant1_out1_1,
              end_rsvd => Logical_Operator_out1_1,
              data_out => y,  -- ufix3
              valid_out => interleaver_dut_out2
              );

  u_bit_mapping : bit_mapping
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb => enb,
              input_sequence => y,  -- ufix3
              amplitude => From_out1,  -- uint8
              inphase => bit_mapping_out1,  -- sfix25_En15
              quadrature => bit_mapping_out2  -- sfix25_En15
              );

  u_bb_shaping1 : bb_shaping1
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_1_1 => enb_1_1_1,
              inphase => std_logic_vector(Switch_out1_1),  -- sfix25_En15
              quadrature => std_logic_vector(Switch1_out1_1),  -- sfix25_En15
              i_filtered => bb_shaping1_out1,  -- sfix45_En31
              q_filtered => bb_shaping1_out2  -- sfix45_En31
              );

  start_1 <= start;

  
  Compare_To_Constant1_out1 <= '1' WHEN HDL_Counter_out1 <= to_unsigned(16#FD20#, 16) ELSE
      '0';

  Logical_Operator_out1 <=  NOT Compare_To_Constant1_out1;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 64800
  HDL_Counter_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        HDL_Counter_out1 <= to_unsigned(16#0000#, 16);
      ELSIF enb_1_8_0 = '1' THEN
        IF Logical_Operator_out1 = '1' THEN 
          HDL_Counter_out1 <= to_unsigned(16#0000#, 16);
        ELSIF valid = '1' THEN 
          IF HDL_Counter_out1 >= to_unsigned(16#FD20#, 16) THEN 
            HDL_Counter_out1 <= to_unsigned(16#0000#, 16);
          ELSE 
            HDL_Counter_out1 <= HDL_Counter_out1 + to_unsigned(16#0001#, 16);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  Compare_To_Constant2_out1 <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#BD18#, 16) ELSE
      '0';

  delayMatch7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        Compare_To_Constant2_out1_1 <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        Compare_To_Constant2_out1_1 <= Compare_To_Constant2_out1;
      END IF;
    END IF;
  END PROCESS delayMatch7_process;


  valid_2 <= valid_1;

  delayMatch1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        valid_3 <= '0';
      ELSIF enb = '1' THEN
        valid_3 <= valid_2;
      END IF;
    END IF;
  END PROCESS delayMatch1_process;


  delayMatch8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        delayMatch8_reg(0) <= '0';
        delayMatch8_reg(1) <= '0';
        delayMatch8_reg(2) <= '0';
        delayMatch8_reg(3) <= '0';
        delayMatch8_reg(4) <= '0';
        delayMatch8_reg(5) <= '0';
        delayMatch8_reg(6) <= '0';
        delayMatch8_reg(7) <= '0';
      ELSIF enb = '1' THEN
        delayMatch8_reg(0) <= delayMatch8_reg_next(0);
        delayMatch8_reg(1) <= delayMatch8_reg_next(1);
        delayMatch8_reg(2) <= delayMatch8_reg_next(2);
        delayMatch8_reg(3) <= delayMatch8_reg_next(3);
        delayMatch8_reg(4) <= delayMatch8_reg_next(4);
        delayMatch8_reg(5) <= delayMatch8_reg_next(5);
        delayMatch8_reg(6) <= delayMatch8_reg_next(6);
        delayMatch8_reg(7) <= delayMatch8_reg_next(7);
      END IF;
    END IF;
  END PROCESS delayMatch8_process;

  stream_adapt_out1_1 <= delayMatch8_reg(7);
  delayMatch8_reg_next(0) <= stream_adapt_out1;
  delayMatch8_reg_next(1) <= delayMatch8_reg(0);
  delayMatch8_reg_next(2) <= delayMatch8_reg(1);
  delayMatch8_reg_next(3) <= delayMatch8_reg(2);
  delayMatch8_reg_next(4) <= delayMatch8_reg(3);
  delayMatch8_reg_next(5) <= delayMatch8_reg(4);
  delayMatch8_reg_next(6) <= delayMatch8_reg(5);
  delayMatch8_reg_next(7) <= delayMatch8_reg(6);

  serial_out_1 <= serial_out;

  delayMatch_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        serial_out_2 <= '0';
      ELSIF enb = '1' THEN
        serial_out_2 <= serial_out_1;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  
  Switch2_out1 <= stream_adapt_out1_1 WHEN valid_3 = '0' ELSE
      serial_out_2;

  delayMatch9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        delayMatch9_reg(0) <= '0';
        delayMatch9_reg(1) <= '0';
        delayMatch9_reg(2) <= '0';
        delayMatch9_reg(3) <= '0';
        delayMatch9_reg(4) <= '0';
        delayMatch9_reg(5) <= '0';
        delayMatch9_reg(6) <= '0';
        delayMatch9_reg(7) <= '0';
        delayMatch9_reg(8) <= '0';
        delayMatch9_reg(9) <= '0';
        delayMatch9_reg(10) <= '0';
        delayMatch9_reg(11) <= '0';
        delayMatch9_reg(12) <= '0';
        delayMatch9_reg(13) <= '0';
        delayMatch9_reg(14) <= '0';
        delayMatch9_reg(15) <= '0';
      ELSIF enb = '1' THEN
        delayMatch9_reg(0) <= delayMatch9_reg_next(0);
        delayMatch9_reg(1) <= delayMatch9_reg_next(1);
        delayMatch9_reg(2) <= delayMatch9_reg_next(2);
        delayMatch9_reg(3) <= delayMatch9_reg_next(3);
        delayMatch9_reg(4) <= delayMatch9_reg_next(4);
        delayMatch9_reg(5) <= delayMatch9_reg_next(5);
        delayMatch9_reg(6) <= delayMatch9_reg_next(6);
        delayMatch9_reg(7) <= delayMatch9_reg_next(7);
        delayMatch9_reg(8) <= delayMatch9_reg_next(8);
        delayMatch9_reg(9) <= delayMatch9_reg_next(9);
        delayMatch9_reg(10) <= delayMatch9_reg_next(10);
        delayMatch9_reg(11) <= delayMatch9_reg_next(11);
        delayMatch9_reg(12) <= delayMatch9_reg_next(12);
        delayMatch9_reg(13) <= delayMatch9_reg_next(13);
        delayMatch9_reg(14) <= delayMatch9_reg_next(14);
        delayMatch9_reg(15) <= delayMatch9_reg_next(15);
      END IF;
    END IF;
  END PROCESS delayMatch9_process;

  From1_out1 <= delayMatch9_reg(15);
  delayMatch9_reg_next(0) <= start_1;
  delayMatch9_reg_next(1) <= delayMatch9_reg(0);
  delayMatch9_reg_next(2) <= delayMatch9_reg(1);
  delayMatch9_reg_next(3) <= delayMatch9_reg(2);
  delayMatch9_reg_next(4) <= delayMatch9_reg(3);
  delayMatch9_reg_next(5) <= delayMatch9_reg(4);
  delayMatch9_reg_next(6) <= delayMatch9_reg(5);
  delayMatch9_reg_next(7) <= delayMatch9_reg(6);
  delayMatch9_reg_next(8) <= delayMatch9_reg(7);
  delayMatch9_reg_next(9) <= delayMatch9_reg(8);
  delayMatch9_reg_next(10) <= delayMatch9_reg(9);
  delayMatch9_reg_next(11) <= delayMatch9_reg(10);
  delayMatch9_reg_next(12) <= delayMatch9_reg(11);
  delayMatch9_reg_next(13) <= delayMatch9_reg(12);
  delayMatch9_reg_next(14) <= delayMatch9_reg(13);
  delayMatch9_reg_next(15) <= delayMatch9_reg(14);

  
  Compare_To_Constant_out1 <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#BDD8#, 16) ELSE
      '0';

  delayMatch10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        delayMatch10_reg(0) <= '0';
        delayMatch10_reg(1) <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        delayMatch10_reg(0) <= delayMatch10_reg_next(0);
        delayMatch10_reg(1) <= delayMatch10_reg_next(1);
      END IF;
    END IF;
  END PROCESS delayMatch10_process;

  Compare_To_Constant_out1_1 <= delayMatch10_reg(1);
  delayMatch10_reg_next(0) <= Compare_To_Constant_out1;
  delayMatch10_reg_next(1) <= delayMatch10_reg(0);

  ldpc_encoder_out2_1 <= ldpc_encoder_out2;

  delayMatch2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        ldpc_encoder_out2_2 <= '0';
      ELSIF enb = '1' THEN
        ldpc_encoder_out2_2 <= ldpc_encoder_out2_1;
      END IF;
    END IF;
  END PROCESS delayMatch2_process;


  
  Switch3_out1 <= Switch2_out1 WHEN ldpc_encoder_out2_2 = '0' ELSE
      ldpc_encoder_out1;

  delayMatch11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        delayMatch11_reg(0) <= '0';
        delayMatch11_reg(1) <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        delayMatch11_reg(0) <= delayMatch11_reg_next(0);
        delayMatch11_reg(1) <= delayMatch11_reg_next(1);
      END IF;
    END IF;
  END PROCESS delayMatch11_process;

  Compare_To_Constant1_out1_1 <= delayMatch11_reg(1);
  delayMatch11_reg_next(0) <= Compare_To_Constant1_out1;
  delayMatch11_reg_next(1) <= delayMatch11_reg(0);

  delayMatch12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        delayMatch12_reg(0) <= '0';
        delayMatch12_reg(1) <= '0';
      ELSIF enb_1_8_0 = '1' THEN
        delayMatch12_reg(0) <= delayMatch12_reg_next(0);
        delayMatch12_reg(1) <= delayMatch12_reg_next(1);
      END IF;
    END IF;
  END PROCESS delayMatch12_process;

  Logical_Operator_out1_1 <= delayMatch12_reg(1);
  delayMatch12_reg_next(0) <= Logical_Operator_out1;
  delayMatch12_reg_next(1) <= delayMatch12_reg(0);

  delayMatch14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        delayMatch14_reg(0) <= '0';
        delayMatch14_reg(1) <= '0';
        delayMatch14_reg(2) <= '0';
        delayMatch14_reg(3) <= '0';
        delayMatch14_reg(4) <= '0';
        delayMatch14_reg(5) <= '0';
        delayMatch14_reg(6) <= '0';
        delayMatch14_reg(7) <= '0';
      ELSIF enb = '1' THEN
        delayMatch14_reg(0) <= delayMatch14_reg_next(0);
        delayMatch14_reg(1) <= delayMatch14_reg_next(1);
        delayMatch14_reg(2) <= delayMatch14_reg_next(2);
        delayMatch14_reg(3) <= delayMatch14_reg_next(3);
        delayMatch14_reg(4) <= delayMatch14_reg_next(4);
        delayMatch14_reg(5) <= delayMatch14_reg_next(5);
        delayMatch14_reg(6) <= delayMatch14_reg_next(6);
        delayMatch14_reg(7) <= delayMatch14_reg_next(7);
      END IF;
    END IF;
  END PROCESS delayMatch14_process;

  interleaver_dut_out2_1 <= delayMatch14_reg(7);
  delayMatch14_reg_next(0) <= interleaver_dut_out2;
  delayMatch14_reg_next(1) <= delayMatch14_reg(0);
  delayMatch14_reg_next(2) <= delayMatch14_reg(1);
  delayMatch14_reg_next(3) <= delayMatch14_reg(2);
  delayMatch14_reg_next(4) <= delayMatch14_reg(3);
  delayMatch14_reg_next(5) <= delayMatch14_reg(4);
  delayMatch14_reg_next(6) <= delayMatch14_reg(5);
  delayMatch14_reg_next(7) <= delayMatch14_reg(6);

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        interleaver_dut_out2_2 <= '0';
      ELSIF enb = '1' THEN
        interleaver_dut_out2_2 <= interleaver_dut_out2_1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  interleaver_dut_out2_dtc <= signed(resize(unsigned'(interleaver_dut_out2_2 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'), 25));

  amplitude_unsigned <= unsigned(amplitude);

  delayMatch13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        delayMatch13_reg(0) <= to_unsigned(16#00#, 8);
        delayMatch13_reg(1) <= to_unsigned(16#00#, 8);
        delayMatch13_reg(2) <= to_unsigned(16#00#, 8);
      ELSIF enb_1_8_0 = '1' THEN
        delayMatch13_reg(0) <= delayMatch13_reg_next(0);
        delayMatch13_reg(1) <= delayMatch13_reg_next(1);
        delayMatch13_reg(2) <= delayMatch13_reg_next(2);
      END IF;
    END IF;
  END PROCESS delayMatch13_process;

  amplitude_1 <= delayMatch13_reg(2);
  delayMatch13_reg_next(0) <= amplitude_unsigned;
  delayMatch13_reg_next(1) <= delayMatch13_reg(0);
  delayMatch13_reg_next(2) <= delayMatch13_reg(1);

  From_out1 <= std_logic_vector(amplitude_1);

  bit_mapping_out1_signed <= signed(bit_mapping_out1);

  
  Switch_out1 <= interleaver_dut_out2_dtc WHEN interleaver_dut_out2_2 = '0' ELSE
      bit_mapping_out1_signed;

  interleaver_dut_out2_dtc_1 <= signed(resize(unsigned'(interleaver_dut_out2_2 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'), 25));

  bit_mapping_out2_signed <= signed(bit_mapping_out2);

  
  Switch1_out1 <= interleaver_dut_out2_dtc_1 WHEN interleaver_dut_out2_2 = '0' ELSE
      bit_mapping_out2_signed;

  FIR_Interpolation_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        FIR_Interpolation_bypass_reg <= to_signed(16#0000000#, 25);
      ELSIF enb_1_8_1 = '1' THEN
        FIR_Interpolation_bypass_reg <= Switch_out1;
      END IF;
    END IF;
  END PROCESS FIR_Interpolation_bypass_process;

  
  Switch_out1_1 <= Switch_out1 WHEN enb_1_8_1 = '1' ELSE
      FIR_Interpolation_bypass_reg;

  FIR_Interpolation1_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset_x = '1' THEN
        FIR_Interpolation1_bypass_reg <= to_signed(16#0000000#, 25);
      ELSIF enb_1_8_1 = '1' THEN
        FIR_Interpolation1_bypass_reg <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS FIR_Interpolation1_bypass_process;

  
  Switch1_out1_1 <= Switch1_out1 WHEN enb_1_8_1 = '1' ELSE
      FIR_Interpolation1_bypass_reg;

  ce_out <= enb_1_1_1;

  inphase <= bb_shaping1_out1;

  quadrature <= bb_shaping1_out2;

END rtl;

