open_system('base_band_shaping_model');
open_system('gm_base_band_shaping_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_base_band_shaping_model/bb_shaping/FIR Interpolation', 'user2');
annotate_port('gm_base_band_shaping_model/bb_shaping/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('base_band_shaping_model/bb_shaping/FIR Interpolation', 'user2');
annotate_port('base_band_shaping_model/bb_shaping/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_base_band_shaping_model/bb_shaping/FIR Interpolation', 'user2');
annotate_port('gm_base_band_shaping_model/bb_shaping/FIR Interpolation', 1, 1, 'Block not characterized');
hilite_system('base_band_shaping_model/bb_shaping/FIR Interpolation', 'user2');
annotate_port('base_band_shaping_model/bb_shaping/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_base_band_shaping_model/bb_shaping/FIR Interpolation1', 'user2');
annotate_port('gm_base_band_shaping_model/bb_shaping/FIR Interpolation1', 1, 1, 'Block not characterized');
hilite_system('base_band_shaping_model/bb_shaping/FIR Interpolation1', 'user2');
annotate_port('base_band_shaping_model/bb_shaping/FIR Interpolation1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_base_band_shaping_model/bb_shaping/FIR Interpolation1', 'user2');
annotate_port('gm_base_band_shaping_model/bb_shaping/FIR Interpolation1', 1, 1, 'Block not characterized');
hilite_system('base_band_shaping_model/bb_shaping/FIR Interpolation1', 'user2');
annotate_port('base_band_shaping_model/bb_shaping/FIR Interpolation1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('base_band_shaping_model/bb_shaping/FIR Interpolation', 'user2');
annotate_port('base_band_shaping_model/bb_shaping/FIR Interpolation', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('base_band_shaping_model/bb_shaping/FIR Interpolation1', 'user2');
annotate_port('base_band_shaping_model/bb_shaping/FIR Interpolation1', 1, 1, 'Block not characterized');
