open_system('Copy_of_ldpc_dvbs2_model_v2');
open_system('gm_Copy_of_ldpc_dvbs2_model_v2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/fsm_select_xor/fsm_select_xor', 'user2');
annotate_port('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/fsm_select_xor/fsm_select_xor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/fsm_select_xor/fsm_select_xor', 'user2');
annotate_port('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/fsm_select_xor/fsm_select_xor', 1, 1, 'Block not characterized');
hilite_system('Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/fsm_select_xor', 'user2');
annotate_port('Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/fsm_select_xor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 'user2');
annotate_port('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, 'Block not characterized');
hilite_system('Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 'user2');
annotate_port('Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses1', 'user2');
annotate_port('gm_Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses1', 1, 1, 'Block not characterized');
hilite_system('Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses', 'user2');
annotate_port('Copy_of_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses', 1, 1, 'Block not characterized');
