open_system('bit_mapping_model');
open_system('gm_bit_mapping_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bit_mapping_model/bit_mapping/Divide', 'user2');
annotate_port('gm_bit_mapping_model/bit_mapping/Divide', 1, 1, 'Block not characterized');
hilite_system('bit_mapping_model/bit_mapping/Divide', 'user2');
annotate_port('bit_mapping_model/bit_mapping/Divide', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bit_mapping_model/bit_mapping/angle_selector/angle_selector', 'user2');
annotate_port('gm_bit_mapping_model/bit_mapping/angle_selector/angle_selector', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bit_mapping_model/bit_mapping/angle_selector/angle_selector', 'user2');
annotate_port('gm_bit_mapping_model/bit_mapping/angle_selector/angle_selector', 1, 1, 'Block not characterized');
hilite_system('bit_mapping_model/bit_mapping/angle_selector', 'user2');
annotate_port('bit_mapping_model/bit_mapping/angle_selector', 1, 1, 'Block not characterized');
