-- -------------------------------------------------------------
-- 
-- File Name: /Users/wardo/Desktop/Drawer/TelecomThesis/DVB-S2/src/transmitter/3-FEC/codegen/interleave/hdlsrc/interleave_fixpt_pkg.vhd
-- Created: 2020-10-19 20:22:12
-- 
-- Generated by MATLAB 9.9, MATLAB Coder 5.1 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE interleave_fixpt_pkg IS
  TYPE vector_of_signed64 IS ARRAY (NATURAL RANGE <>) OF signed(63 DOWNTO 0);
END interleave_fixpt_pkg;

