-- -------------------------------------------------------------
-- 
-- File Name: /Users/wardo/Desktop/Drawer/TelecomThesis/DVB-S2/src/transmitter/3-FEC/codegen/interleave/hdlsrc/interleave_fixpt.vhd
-- Created: 2020-10-19 20:22:12
-- 
-- Generated by MATLAB 9.9, MATLAB Coder 5.1 and HDL Coder 3.17
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: interleave_fixpt
-- Source Path: interleave_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.interleave_fixpt_pkg.ALL;

ENTITY interleave_fixpt IS
  PORT( message                           :   IN    std_logic_vector(0 TO 64799);  -- ufix1 [64800]
        codeword                          :   OUT   std_logic_vector(0 TO 64799)  -- ufix1 [64800]
        );
END interleave_fixpt;


ARCHITECTURE rtl OF interleave_fixpt IS

BEGIN
  interleave_fixpt_1_output : PROCESS (message)
    VARIABLE codeword1 : std_logic_vector(0 TO 64799);
    VARIABLE cast : vector_of_signed64(0 TO 16199);
    VARIABLE add_cast : vector_of_signed64(0 TO 16199);
    VARIABLE add_cast_0 : vector_of_signed64(0 TO 16199);
    VARIABLE add_cast_1 : vector_of_signed64(0 TO 16199);
  BEGIN
    --HDL code generation from MATLAB function: interleave_fixpt
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --                                                                          %
    --           Generated by MATLAB 9.9 and Fixed-Point Designer 7.1           %
    --                                                                          %
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --INTERLEAVE For 8PSK, 16APSK, and 32APSK modulation formats, the output of 
    -- the LDPC encoder shall be bit interleaved using a block interleaver.
    -- DVBS-2 Section 5.3.3 Bit Interleaver

    FOR i IN 0 TO 16199 LOOP
      cast(i) := resize(to_signed(i, 32) & '0' & '0', 64);
      codeword1(to_integer(resize(cast(i), 31))) := message(i);
      add_cast(i) := resize(to_signed(i, 32) & '0' & '0', 64);
      codeword1(to_integer(resize(add_cast(i), 32) + 1)) := message(i + 16200);
      add_cast_0(i) := resize(to_signed(i, 32) & '0' & '0', 64);
      codeword1(to_integer(resize(add_cast_0(i), 32) + 2)) := message(i + 32400);
      add_cast_1(i) := resize(to_signed(i, 32) & '0' & '0', 64);
      codeword1(to_integer(resize(add_cast_1(i), 32) + 3)) := message(i + 48600);
    END LOOP;

    codeword <= codeword1;
  END PROCESS interleave_fixpt_1_output;


END rtl;

