open_system('transmitter');
open_system('gm_transmitter');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bb_shaping1', 'user2');
annotate_port('gm_transmitter/tran_dut/bb_shaping1', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('transmitter/tran_dut/bb_shaping1', 'user2');
annotate_port('transmitter/tran_dut/bb_shaping1', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/interleaver_dut/interleaver/interleaver', 'user2');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/interleaver/interleaver', 1, 1, 'MATLAB blocks and Stateflow charts can be clock-rate pipelined only if they are stateless. For MATLAB blocks, considering removing use of persistent variables');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/interleaver_dut/interleaver/interleaver', 'user2');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/interleaver/interleaver', 1, 1, 'MATLAB blocks and Stateflow charts can be clock-rate pipelined only if they are stateless. For MATLAB blocks, considering removing use of persistent variables');
hilite_system('transmitter/tran_dut/interleaver_dut/interleaver', 'user2');
annotate_port('transmitter/tran_dut/interleaver_dut/interleaver', 1, 1, 'MATLAB blocks and Stateflow charts can be clock-rate pipelined only if they are stateless. For MATLAB blocks, considering removing use of persistent variables');
