-- -------------------------------------------------------------
-- 
-- File Name: D:\Documents\DVBS2\DVBS2\src\simulink\hdl_transmitter\hdlsrc\transmitter\interleaver_dut.vhd
-- Created: 2021-01-03 15:49:57
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: interleaver_dut
-- Source Path: transmitter/tran_dut/interleaver_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY interleaver_dut IS
  PORT( clk                               :   IN    std_logic;
        reset_x                           :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        input_bit                         :   IN    std_logic;
        start                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        data_out                          :   OUT   std_logic_vector(0 TO 2);  -- ufix1 [3]
        valid_out                         :   OUT   std_logic
        );
END interleaver_dut;


ARCHITECTURE rtl OF interleaver_dut IS

  -- Component Declarations
  COMPONENT interleaver
    PORT( clk                             :   IN    std_logic;
          reset_x                         :   IN    std_logic;
          enb_1_8_0                       :   IN    std_logic;
          input_bit                       :   IN    std_logic;
          start                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          data                            :   OUT   std_logic_vector(0 TO 2);  -- ufix1 [3]
          valid                           :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : interleaver
    USE ENTITY work.interleaver(rtl);

  -- Signals
  SIGNAL data                             : std_logic_vector(0 TO 2);  -- ufix1 [3]
  SIGNAL valid                            : std_logic;

BEGIN
  u_interleaver : interleaver
    PORT MAP( clk => clk,
              reset_x => reset_x,
              enb_1_8_0 => enb_1_8_0,
              input_bit => input_bit,
              start => start,  -- uint8
              data => data,  -- ufix1 [3]
              valid => valid
              );

  data_out <= data;

  valid_out <= valid;

END rtl;

