SLStudio.Utils.RemoveHighlighting(get_param('ldpc_dvbs2_model_v2', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ldpc_dvbs2_model_v2', 'handle'));
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay2', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/reset_in', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay_lowered', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/reset_out', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Assignment', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Assignment', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/Assignment', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Logical Operator1', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Selector', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Switch', 0, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/p2s', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses', 1, 1, '');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses/addresses1', 1, 1, '');
annotate_port('ldpc_dvbs2_model_v2/ldpc_encoder/address_calculator/addresses', 1, 1, '');
