open_system('gm_ldpc_dvbs2_model_v2');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay2', 'user1');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay2', 0, 1, 'cp : 0.46 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/reset_in', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/reset_in', 0, 1, 'cp : 2.4985 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay_lowered', 'user1');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Delay_lowered', 1, 1, 'cp : 2.6625 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/reset_out', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/reset_out', 0, 1, 'cp : 0.877 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Assignment', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Assignment', 0, 1, 'cp : 2.2555 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Logical Operator1', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Logical Operator1', 0, 1, 'cp : 1.7825 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Selector', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Selector', 0, 1, 'cp : 0.877 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Switch', 'user2');
annotate_port('gm_ldpc_dvbs2_model_v2/ldpc_encoder/Switch', 0, 1, 'cp : 2.2555 ns');
