# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
# IP: The module: 'simcycle_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
# IP: The module: 'simcycle_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/wardo/Documents/Matlab Projects/Cosimulation and FPGA in the loop tutorial/codegen/mlhdlc_sysobj_ex/fil/mlhdlc_sysobj_ex_fixpt_fil/fpgaproj/mlhdlc_sysobj_ex_fixpt_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
