%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.9 and Fixed-Point Designer 7.1           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function codeword = interleave_fixpt(message)
%INTERLEAVE For 8PSK, 16APSK, and 32APSK modulation formats, the output of 
% the LDPC encoder shall be bit interleaved using a block interleaver.
% DVBS-2 Section 5.3.3 Bit Interleaver
    fm = get_fimath();

    codeword = fi(zeros(size(message)), 0, 1, 0, fm);
    for i = 1:16200
       codeword(4*(i-1)+1) = message(i);
       codeword(4*(i-1)+2) = message(16200+i);
       codeword(4*(i-1)+3) = message(2*16200+i);
       codeword(4*(i-1)+4) = message(3*16200+i);
    end
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
