SLStudio.Utils.RemoveHighlighting(get_param('transmitter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_transmitter', 'handle'));
annotate_port('gm_transmitter/tran_dut/bb_shaping1', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/HDL Counter', 1, 1, '');
annotate_port('transmitter/tran_dut/HDL Counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/Bit Concat', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/Bit Concat', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/Logical Operator2', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/Logical Operator2', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/MATLAB Function', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/MATLAB Function', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/Delay1', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/Delay1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/Delay1', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/Delay1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/p2s/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/p2s', 1, 1, '');
