vlib work
vcom  tran_dut_pac.vhd
vcom  FIR_Interpolation.vhd
vcom  FIR_Interpolation1.vhd
vcom  bb_shaping1.vhd
vcom  p2s.vhd
vcom  output_mask.vhd
vcom  registers.vhd
vcom  shift_and_xor.vhd
vcom  bch_encoder.vhd
vcom  SinglePortRAM_singlebit.vhd
vcom  interleaver_dut.vhd
vcom  addresses.vhd
vcom  address_calculator.vhd
vcom  p2s_block.vhd
vcom  MATLAB_Function.vhd
vcom  ldpc_encoder.vhd
vcom  stream_adapt.vhd
vcom  Cosine_HDL_Optimized.vhd
vcom  angle_selector.vhd
vcom  bit_mapping.vhd
vcom  tran_dut_tc.vhd
vcom  tran_dut.vhd
