SLStudio.Utils.RemoveHighlighting(get_param('transmitter', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_transmitter', 'handle'));
annotate_port('gm_transmitter/tran_dut/bb_shaping1', 1, 1, '');
annotate_port('transmitter/tran_dut/bb_shaping1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/stream_adapt', 1, 1, '');
annotate_port('transmitter/tran_dut/stream_adapt', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/HDL Counter', 1, 1, '');
annotate_port('transmitter/tran_dut/HDL Counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/registers', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/column_counter', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/column_counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/Single Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/Single Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/Single Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/Single Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/Single Port RAM1', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/Single Port RAM1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/Single Port RAM1', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/Single Port RAM1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/interleaver_dut/row_counter', 1, 1, '');
annotate_port('transmitter/tran_dut/interleaver_dut/row_counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/Delay', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/Delay', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/slot_counter', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/slot_counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/address_calculator/bit_counter1', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/address_calculator/bit_counter1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/stream_adapt/frame_counter', 1, 1, '');
annotate_port('transmitter/tran_dut/stream_adapt/frame_counter', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/p2s/p2s', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/p2s', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, '');
annotate_port('gm_transmitter/tran_dut/bch_encoder/registers/registers', 1, 1, '');
annotate_port('transmitter/tran_dut/bch_encoder/registers', 1, 1, '');
