open_system('transmitter');
open_system('gm_transmitter');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/registers', 'user1');
hilite_system('transmitter/tran_dut/bch_encoder/registers', 'user1');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat1/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat10/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat11/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat2/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat3/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat4/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat5/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat6/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat7/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat8/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Logical Operator', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Logical Operator', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user3');
cs.HiliteType = 'user3';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'yellow';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user3');
hilite_system('transmitter/tran_dut/ldpc_encoder/ram_bank/ram_repeat9/Dual Port RAM', 'user3');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/registers/registers', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_transmitter/tran_dut/bch_encoder/registers/registers', 'user1');
hilite_system('transmitter/tran_dut/bch_encoder/registers', 'user1');
