vlib work
vmap -c
vcom  tran_dut_pac.vhd
vcom  FIR_Interpolation.vhd
vcom  FIR_Interpolation1.vhd
vcom  bb_shaping1.vhd
vcom  p2s.vhd
vcom  registers.vhd
vcom  shift_and_xor.vhd
vcom  output_mask.vhd
vcom  bch_encoder.vhd
vcom  SinglePortRAM_singlebit.vhd
vcom  interleaver_dut.vhd
vcom  addresses.vhd
vcom  address_calculator.vhd
vcom  DualPortRAM_singlebit.vhd
vcom  ram_repeat.vhd
vcom  ram_repeat1.vhd
vcom  ram_repeat10.vhd
vcom  ram_repeat11.vhd
vcom  ram_repeat2.vhd
vcom  ram_repeat3.vhd
vcom  ram_repeat4.vhd
vcom  ram_repeat5.vhd
vcom  ram_repeat6.vhd
vcom  ram_repeat7.vhd
vcom  ram_repeat8.vhd
vcom  ram_repeat9.vhd
vcom  ram_bank.vhd
vcom  select_address.vhd
vcom  ldpc_encoder.vhd
vcom  stream_adapt.vhd
vcom  Cosine_HDL_Optimized.vhd
vcom  angle_selector.vhd
vcom  bit_mapping.vhd
vcom  tran_dut_tc.vhd
vcom  tran_dut.vhd
