open_system('bch_encoder_model');
open_system('gm_bch_encoder_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/output_mask/output_mask', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/output_mask/output_mask', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/output_mask/output_mask', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/output_mask/output_mask', 1, 1, 'Block not characterized');
hilite_system('bch_encoder_model/bch_encoder/output_mask', 'user2');
annotate_port('bch_encoder_model/bch_encoder/output_mask', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/p2s/p2s', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/p2s/p2s', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/p2s/p2s', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/p2s/p2s', 1, 1, 'Block not characterized');
hilite_system('bch_encoder_model/bch_encoder/p2s', 'user2');
annotate_port('bch_encoder_model/bch_encoder/p2s', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/registers/registers', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/registers/registers', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/registers/registers', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/registers/registers', 1, 1, 'Block not characterized');
hilite_system('bch_encoder_model/bch_encoder/registers', 'user2');
annotate_port('bch_encoder_model/bch_encoder/registers', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/shift_and_xor/shift_and_xor', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/shift_and_xor/shift_and_xor', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_bch_encoder_model/bch_encoder/shift_and_xor/shift_and_xor', 'user2');
annotate_port('gm_bch_encoder_model/bch_encoder/shift_and_xor/shift_and_xor', 1, 1, 'Block not characterized');
hilite_system('bch_encoder_model/bch_encoder/shift_and_xor', 'user2');
annotate_port('bch_encoder_model/bch_encoder/shift_and_xor', 1, 1, 'Block not characterized');
