open_system('gm_interleaver_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interleaver_model/interleaver_dut/interleaver', 'user2');
annotate_port('gm_interleaver_model/interleaver_dut/interleaver', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_interleaver_model/interleaver_dut/interleaver/interleaver', 'user2');
annotate_port('gm_interleaver_model/interleaver_dut/interleaver/interleaver', 0, 1, 'cp : 0 ns');
