SLStudio.Utils.RemoveHighlighting(get_param('bit_mapping_model', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_bit_mapping_model', 'handle'));
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized', 1, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/angle_selector', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Divide', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Divide', 1, 1, '');
annotate_port('bit_mapping_model/bit_mapping/Divide', 1, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/Amp50', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/CastU16En21', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/CastU16En31', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/CastU16En4', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/Look-Up Table1', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/QuadHandle1', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/QuadHandle21', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/Saturation1', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/Switch1', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/insig1', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/p50mA', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/Cosine HDL Optimized/PipelineRegister1', 1, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/angle_selector/angle_selector', 0, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/angle_selector/angle_selector', 1, 1, '');
annotate_port('gm_bit_mapping_model/bit_mapping/angle_selector/angle_selector', 1, 1, '');
annotate_port('bit_mapping_model/bit_mapping/angle_selector', 1, 1, '');
