load_package flow
project_new -overwrite tran_dut_fil
set_global_assignment -name FAMILY  {Cyclone V}
set_global_assignment -name DEVICE  {5CSEMA4U23C6}
set_global_assignment -name CYCLONEII_OPTIMIZATION_TECHNIQUE SPEED
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/tran_dut_pac.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/FIR_Interpolation.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/FIR_Interpolation1.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/bb_shaping1.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/p2s.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/registers.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/shift_and_xor.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/output_mask.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/bch_encoder.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/SinglePortRAM_singlebit.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/interleaver_dut.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/addresses.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/address_calculator.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/DualPortRAM_singlebit.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat1.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat10.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat11.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat2.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat3.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat4.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat5.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat6.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat7.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat8.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_repeat9.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ram_bank.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/select_address.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/ldpc_encoder.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/stream_adapt.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/Cosine_HDL_Optimized.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/angle_selector.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/bit_mapping.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/tran_dut_tc.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/hdlsrc/transmitter/tran_dut.vhd
set_global_assignment -name USE_TIMEQUEST_TIMING_ANALYZER ON
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/MWClkMgr.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/MWAJTAG.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/MWDPRAM.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/FILUDPCRC.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/FILPktMUX.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/FILCmdProc.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/MWAsyncFIFO.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/FILDataProc.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/MWPKTBuffer.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/MWUDPPKTBuilder.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/FILPktProc.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/FILCommLayer.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/mwfil_dpscram.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/mwfil_udfifo.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/mwfil_bus2dut.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/mwfil_chifcore.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/mwfil_controller.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/mwfil_dut2bus.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/tran_dut_wrapper.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/mwfil_chiftop.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/FILCore.vhd
set_global_assignment -name VHDL_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/tran_dut_fil.vhd
source /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/tran_dut_fil.qsf
set_global_assignment -name SDC_FILE /home/wardo/Documents/DVBS2/DVBS2/src/transmitter/altera_files/fil_prj/filsrc/tran_dut_fil.sdc
set_global_assignment -name USE_TIMEQUEST_TIMING_ANALYZER ON
set_global_assignment -name TOP_LEVEL_ENTITY tran_dut_fil
execute_flow -analysis_and_elaboration
project_close
