open_system('gm_Copy_of_interleaver_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 'user2');
annotate_port('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 0, 1, 'cp : 3.1425 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_interleaver_model/interleaver_dut/Bit Concat', 'user1');
annotate_port('gm_Copy_of_interleaver_model/interleaver_dut/Bit Concat', 0, 1, 'cp : 3.1425 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 'user1');
annotate_port('Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 0, 1, 'cp : 3.1425 ns');
