open_system('Copy_of_interleaver_model');
open_system('gm_Copy_of_interleaver_model');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 'user2');
annotate_port('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 1, 1, 'Block not characterized');
hilite_system('Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 'user2');
annotate_port('Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 'user2');
annotate_port('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 1, 1, 'Block not characterized');
hilite_system('Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 'user2');
annotate_port('Copy_of_interleaver_model/interleaver_dut/Single Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 'user2');
annotate_port('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 1, 1, 'Block not characterized');
hilite_system('Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 'user2');
annotate_port('Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 'user2');
annotate_port('gm_Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 1, 1, 'Block not characterized');
hilite_system('Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 'user2');
annotate_port('Copy_of_interleaver_model/interleaver_dut/Single Port RAM1', 1, 1, 'Block not characterized');
